접속사 및 기타 부분의 표현 수정
CppKorea/CodeOfConduct pull request #9
Opened 2021-07-13 13:54 UTC by GabrielKim

1. 정보가 어떤 정보인지 불분명한 곳을 수정
2. "CoC 이해와 한계 부분"의 문장 중 일부 접속사 빠짐을 수정

2021-07-13 14:02 UTC, utilForever requested changes
띄어쓰기가 잘못된 부분이 있습니다. 확인 부탁드립니다.

2021-07-13 14:02 UTC, utilForever commented on README.md
> +- 그 사람의 지인이라고 해서 함부로 개인정보를 말할 수 있는 것은 아닙니다.
```suggestion
- 그 사람의 지인이라고 해서 함부로 개인 정보를 말할 수 있는 것은 아닙니다.
```

2021-07-13 14:13 UTC, GabrielKim commented on README.md
> +- 그 사람의 지인이라고 해서 함부로 개인정보를 말할 수 있는 것은 아닙니다.
이 부분도 반영하겠습니다.

2021-07-13 15:34 UTC, utilForever commented on README.md
> +- 그 사람의 지인이라고 해서 함부로 개인정보를 말할 수 있는 것은 아닙니다.
사전을 찾아보니 대부분 띄어 쓰더군요.

2021-07-14 11:14 UTC, luncliff commented
한문으로는 붙어있어도 한글 표기에서는 띄어서 사용하는 군요. 처음 알았습니다. `개인 정보`
https://dic.daum.net/search.do?q=개인정보
https://ko.dict.naver.com/#/entry/koko/89f40d0938354329a55083712ce4d95c

2021-07-14 11:17 UTC, JannLee commented on README.md
> +- 그 사람의 지인이라고 해서 함부로 개인정보를 말할 수 있는 것은 아닙니다.
저는 띄어 쓰던 안띄어 쓰던 크게 문제 삼을 만한 내용은 아니지 않을까 싶은데,
대세에 따라 띄어 쓰는 것에 한표하겠습니다.

2021-07-14 14:08 UTC, utilForever approved these changes
LGTM now. Thanks for your work! 🕊️

2021-07-14 14:18 UTC, luncliff approved these changes

2021-07-14 22:12 UTC, JannLee approved these changes

2021-07-14 23:09 UTC, merged